### ISSUE TITLE
Animation Token System Implementation

### ISSUE THREAD

**Issue by WTWalters** [WTWalters/neural-nexus-strategies#21]
# Animation Token System Implementation

## Overview
Following ADR-003 Design System guidelines, we need to implement a comprehensive animation token system that provides consistent motion across the application.

### 1. Animation Token Structure
```typescript
// src/styles/tokens/animations.ts

// Duration tokens
const durations = {
  instant: '0ms',
  fast: '150ms',
  normal: '250ms',
  slow: '350ms',
  slower: '500ms',
} as const;

// Easing tokens
const easings = {
  // Standard easings
  linear: 'linear',
  easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
  easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
  easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  
  // Custom easings
  emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
  emphasizedAccelerate: 'cubic-bezier(0.3, 0.0, 0.8, 0.15)',
} as const;

// Animation keyframes
const keyframes = {
  fadeIn: {
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
  fadeOut: {
    from: { opacity: 1 },
    to: { opacity: 0 },
  },
  slideInRight: {
    from: { transform: 'translateX(100%)' },
    to: { transform: 'translateX(0)' },
  },
  slideOutRight: {
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(100%)' },
  },
  slideInDown: {
    from: { transform: 'translateY(-100%)' },
    to: { transform: 'translateY(0)' },
  },
  slideOutUp: {
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-100%)' },
  },
  scaleUp: {
    from: { transform: 'scale(0.95)' },
    to: { transform: 'scale(1)' },
  },
  scaleDown: {
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(0.95)' },
  },
  spin: {
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
  },
} as const;

// Component-specific animation presets
const components = {
  button: {
    hover: {
      duration: 'var(--animation-duration-fast)',
      easing: 'var(--animation-easing-easeOut)',
    },
    active: {
      duration: 'var(--animation-duration-instant)',
      easing: 'var(--animation-easing-easeIn)',
    },
  },
  dialog: {
    enter: {
      duration: 'var(--animation-duration-normal)',
      easing: 'var(--animation-easing-emphasizedDecelerate)',
    },
    exit: {
      duration: 'var(--animation-duration-fast)',
      easing: 'var(--animation-easing-emphasizedAccelerate)',
    },
  },
  tooltip: {
    enter: {
      duration: 'var(--animation-duration-fast)',
      easing: 'var(--animation-easing-easeOut)',
    },
    exit: {
      duration: 'var(--animation-duration-instant)',
      easing: 'var(--animation-easing-easeIn)',
    },
  },
  dropdown: {
    enter: {
      duration: 'var(--animation-duration-normal)',
      easing: 'var(--animation-easing-easeOut)',
    },
    exit: {
      duration: 'var(--animation-duration-fast)',
      easing: 'var(--animation-easing-easeIn)',
    },
  },
} as const;

export const animations = {
  durations,
  easings,
  keyframes,
  components,
} as const;

// Type exports
export type AnimationDurations = typeof durations;
export type AnimationEasings = typeof easings;
export type AnimationKeyframes = typeof keyframes;
export type AnimationComponents = typeof components;
```

### 2. CSS Custom Properties Setup
```typescript
// src/styles/theme/animations.css

:root {
  /* Duration tokens */
  --animation-duration-instant: 0ms;
  --animation-duration-fast: 150ms;
  --animation-duration-normal: 250ms;
  --animation-duration-slow: 350ms;
  --animation-duration-slower: 500ms;

  /* Easing tokens */
  --animation-easing-linear: linear;
  --animation-easing-easeIn: cubic-bezier(0.4, 0, 1, 1);
  --animation-easing-easeOut: cubic-bezier(0, 0, 0.2, 1);
  --animation-easing-easeInOut: cubic-bezier(0.4, 0, 0.2, 1);
  --animation-easing-emphasizedDecelerate: cubic-bezier(0.05, 0.7, 0.1, 1.0);
  --animation-easing-emphasizedAccelerate: cubic-bezier(0.3, 0.0, 0.8, 0.15);
}
```

### 3. React Animation Hook
```typescript
// src/hooks/useAnimation.ts

import { animations } from '@/styles/tokens/animations';

export function useAnimation(
  component: keyof typeof animations.components,
  state: 'enter' | 'exit' | 'hover' | 'active'
) {
  const componentAnimation = animations.components[component]?.[state];
  
  if (!componentAnimation) {
    return {};
  }

  return {
    transition: `all ${componentAnimation.duration} ${componentAnimation.easing}`,
  };
}
```

### 4. Example Usage

```typescript
// Component implementation
import { useAnimation } from '@/hooks/useAnimation';

function Dialog({ isOpen, children }) {
  const animation = useAnimation('dialog', isOpen ? 'enter' : 'exit');
  
  return (
    <div
      style={{
        ...animation,
        opacity: isOpen ? 1 : 0,
        transform: isOpen ? 'scale(1)' : 'scale(0.95)',
      }}
    >
      {children}
    </div>
  );
}

// CSS implementation
.button {
  transition: all var(--animation-duration-fast) var(--animation-easing-easeOut);
}

.button:hover {
  transform: translateY(-1px);
}
```

## Implementation Steps

1. Create animation token files:
   - [x] `/styles/tokens/animations.ts`
   - [x] `/styles/theme/animations.css`
   - [x] `/hooks/useAnimation.ts`

2. Add type support:
   - [ ] Add animation token types
   - [ ] Update existing component types to use animation tokens

3. Update components to use animation tokens:
   - [ ] Button
   - [ ] Dialog
   - [ ] Dropdown
   - [ ] Tooltip

4. Add documentation:
   - [ ] Animation token usage guide
   - [ ] Component animation examples
   - [ ] Best practices

## Testing Requirements

1. Unit Tests:
   - [ ] Animation token values
   - [ ] useAnimation hook
   - [ ] Component animations

2. Integration Tests:
   - [ ] Component animation behavior
   - [ ] Theme integration
   - [ ] Dynamic animation updates

## Documentation Requirements

1. Add to design system documentation:
   - [ ] Animation principles
   - [ ] Token usage guidelines
   - [ ] Component-specific animations
   - [ ] Performance considerations

Please review this implementation plan and provide any feedback or adjustments needed.
