### ISSUE TITLE
Animation Token System Implementation

### ISSUE THREAD

**Issue by WTWalters** [WTWalters/neural-nexus-strategies#22]
## Animation Token System Implementation

This implements the animation token system following ADR-003 design system guidelines.

### Token Structure

```typescript
// src/styles/tokens/animation.ts

// Duration tokens
const durations = {
  instant: '0ms',
  fastest: '100ms',
  fast: '200ms',
  normal: '300ms',
  slow: '400ms',
  slowest: '500ms',
} as const;

// Easing tokens
const easings = {
  // Standard easings
  linear: 'linear',
  
  // Ease-out (most UI elements)
  easeOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
  easeOutFast: 'cubic-bezier(0.0, 0, 0.1, 1)',
  easeOutSlow: 'cubic-bezier(0.0, 0, 0.3, 1)',
  
  // Ease-in (elements exiting view)
  easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
  easeInFast: 'cubic-bezier(0.3, 0, 1, 1)',
  easeInSlow: 'cubic-bezier(0.5, 0, 1, 1)',
  
  // Ease-in-out (changing states)
  easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easeInOutFast: 'cubic-bezier(0.3, 0, 0.1, 1)',
  easeInOutSlow: 'cubic-bezier(0.5, 0, 0.3, 1)',
} as const;

// Animation preset tokens
const presets = {
  fade: {
    in: {
      from: { opacity: 0 },
      to: { opacity: 1 },
    },
    out: {
      from: { opacity: 1 },
      to: { opacity: 0 },
    },
  },
  slideUp: {
    in: {
      from: { transform: 'translateY(10px)', opacity: 0 },
      to: { transform: 'translateY(0)', opacity: 1 },
    },
    out: {
      from: { transform: 'translateY(0)', opacity: 1 },
      to: { transform: 'translateY(-10px)', opacity: 0 },
    },
  },
  slideDown: {
    in: {
      from: { transform: 'translateY(-10px)', opacity: 0 },
      to: { transform: 'translateY(0)', opacity: 1 },
    },
    out: {
      from: { transform: 'translateY(0)', opacity: 1 },
      to: { transform: 'translateY(10px)', opacity: 0 },
    },
  },
  scale: {
    in: {
      from: { transform: 'scale(0.95)', opacity: 0 },
      to: { transform: 'scale(1)', opacity: 1 },
    },
    out: {
      from: { transform: 'scale(1)', opacity: 1 },
      to: { transform: 'scale(0.95)', opacity: 0 },
    },
  },
} as const;

// Specific component animation configurations
const components = {
  button: {
    hover: {
      duration: 'fast',
      easing: 'easeOut',
    },
    active: {
      duration: 'fastest',
      easing: 'easeOut',
    },
  },
  dialog: {
    enter: {
      duration: 'normal',
      easing: 'easeOut',
      preset: 'slideUp',
    },
    exit: {
      duration: 'fast',
      easing: 'easeIn',
      preset: 'fade',
    },
  },
  tooltip: {
    enter: {
      duration: 'fast',
      easing: 'easeOutFast',
      preset: 'fade',
    },
    exit: {
      duration: 'fastest',
      easing: 'easeIn',
      preset: 'fade',
    },
  },
  menu: {
    enter: {
      duration: 'normal',
      easing: 'easeOutFast',
      preset: 'scale',
    },
    exit: {
      duration: 'fast',
      easing: 'easeIn',
      preset: 'fade',
    },
  },
} as const;

export const animation = {
  durations,
  easings,
  presets,
  components,
} as const;

// Type exports
export type AnimationDurations = typeof durations;
export type AnimationEasings = typeof easings;
export type AnimationPresets = typeof presets;
export type ComponentAnimations = typeof components;
```

### Usage Example

```typescript
import { animation } from '@/styles/tokens/animation';

// In styled-components
const StyledButton = styled.button`
  transition: all ${animation.durations.fast} ${animation.easings.easeOut};
  
  &:hover {
    transform: translateY(-1px);
  }
`;

// In Tailwind classes
const buttonClasses = cx(
  'transition-all',
  'duration-[var(--duration-fast)]',
  'ease-[var(--ease-out)]'
);

// With Framer Motion
const modalVariants = {
  hidden: animation.presets.slideUp.out.from,
  visible: animation.presets.slideUp.in.to,
};
```

### Implementation Steps

1. Create token file:
```bash
mkdir -p src/styles/tokens
touch src/styles/tokens/animation.ts
```

2. Add CSS variables to global styles:
```css
:root {
  /* Durations */
  --duration-instant: 0ms;
  --duration-fastest: 100ms;
  --duration-fast: 200ms;
  --duration-normal: 300ms;
  --duration-slow: 400ms;
  --duration-slowest: 500ms;

  /* Easings */
  --ease-linear: linear;
  --ease-out: cubic-bezier(0.0, 0, 0.2, 1);
  --ease-in: cubic-bezier(0.4, 0, 1, 1);
  --ease-in-out: cubic-bezier(0.4, 0, 0.2, 1);
}
```

3. Add animation token tests:
```typescript
// __tests__/animation.test.ts
import { animation } from '../animation';

describe('Animation Tokens', () => {
  it('has correct duration values', () => {
    expect(animation.durations.fast).toBe('200ms');
  });

  it('has correct easing values', () => {
    expect(animation.easings.easeOut).toBe('cubic-bezier(0.0, 0, 0.2, 1)');
  });

  it('has correct preset structure', () => {
    expect(animation.presets.fade.in).toHaveProperty('from');
    expect(animation.presets.fade.in).toHaveProperty('to');
  });
});
```

### Next Steps

1. [x] Create PR with animation token implementation
2. [ ] Add animation token documentation
3. [ ] Update ADR-003 with animation token details
4. [ ] Create examples of animation token usage
5. [ ] Add to component template guidelines

Please review and provide feedback on this animation token structure.
